services:
  solar:
    build:
      context: .
      dockerfile: docker/Dockerfile.solar
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - PYTHONUNBUFFERED=1

  image:
    build:
      context: .
      dockerfile: docker/Dockerfile.image
    restart: unless-stopped
    ports:
      - "8085:8085"

  layout:
    build:
      context: .
      dockerfile: docker/Dockerfile.layout
    restart: unless-stopped
    ports:
      - "8087:8087"
    volumes:
      - layout_data:/data
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  layout_data:
