// Minimal GFX bitmap font type definitions.
// Compatible with fonts generated by the Adafruit GFX font tools (MIT license).
// No Adafruit_GFX library dependency required.
#pragma once
#include <stdint.h>

#ifndef PROGMEM
#define PROGMEM
#endif

typedef struct {
    uint16_t bitmapOffset; ///< Pointer into GFXfont->bitmap
    uint8_t  width;        ///< Bitmap width in pixels
    uint8_t  height;       ///< Bitmap height in pixels
    uint8_t  xAdvance;     ///< Cursor advance past this glyph
    int8_t   xOffset;      ///< X offset from cursor to glyph UL corner
    int8_t   yOffset;      ///< Y offset from cursor (baseline) to glyph UL corner
} GFXglyph;

typedef struct {
    const uint8_t  *bitmap;  ///< Packed glyph bitmaps
    const GFXglyph *glyph;   ///< Glyph descriptors
    uint16_t        first;   ///< First ASCII code covered
    uint16_t        last;    ///< Last ASCII code covered
    uint8_t         yAdvance;///< Newline distance (pixels)
} GFXfont;
